//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsociacionDetalle
    {
        public int AsociacionId { get; set; }
        public string Banco { get; set; }
        public string BancoCuenta { get; set; }
        public string Moneda { get; set; }
    
        public virtual Asociacion Asociacion { get; set; }
    }
}
