//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financiamiento
    {
        public int FinanciamientoId { get; set; }
        public int AlumnoId { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public decimal Porcentaje { get; set; }
        public int CuotaId { get; set; }
        public decimal Cuota { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Observacion { get; set; }
        public int EstatusId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Cuota Cuota1 { get; set; }
        public virtual Estatus Estatus { get; set; }
    }
}
