//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.GrupoAlumnoConfiguracion = new HashSet<GrupoAlumnoConfiguracion>();
            this.GrupoComprobante = new HashSet<GrupoComprobante>();
        }
    
        public int GrupoId { get; set; }
        public int EmpresaId { get; set; }
        public string Descripcion { get; set; }
        public int SucursalId { get; set; }
        public string SucursalDireccion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int NumeroPagos { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoAlumnoConfiguracion> GrupoAlumnoConfiguracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoComprobante> GrupoComprobante { get; set; }
        public virtual GrupoDetalle GrupoDetalle { get; set; }
    }
}
