//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoComprobante
    {
        public int GrupoComprobanteId { get; set; }
        public int GrupoId { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.TimeSpan HoraRegistro { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual GrupoComprobanteDocumento GrupoComprobanteDocumento { get; set; }
    }
}
