//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdiomaGrupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdiomaGrupo()
        {
            this.IdiomaGrupoAlumno = new HashSet<IdiomaGrupoAlumno>();
        }
    
        public int IdiomaGrupoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> PeriodoId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.TimeSpan> HoraRegistro { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdiomaGrupoAlumno> IdiomaGrupoAlumno { get; set; }
    }
}
