//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaEducativaRequerimiento
    {
        public int OfertaEducativaId { get; set; }
        public int NivelAcademicoId { get; set; }
        public int NoAsignaturas { get; set; }
        public decimal Creditos { get; set; }
    
        public virtual NivelAcademico NivelAcademico { get; set; }
        public virtual OfertaEducativa OfertaEducativa { get; set; }
    }
}
