//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pagare()
        {
            this.PagoPagare = new HashSet<PagoPagare>();
        }
    
        public int PagareId { get; set; }
        public int AlumnoId { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal Importe { get; set; }
        public decimal Interes { get; set; }
        public string Observacion { get; set; }
        public int UsuarioId { get; set; }
        public int EstatusId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual PagareDocumento PagareDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoPagare> PagoPagare { get; set; }
    }
}
