//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboArchivo
    {
        public int SucursalCajaId { get; set; }
        public int ReciboId { get; set; }
        public byte[] Archivo { get; set; }
    
        public virtual Recibo Recibo { get; set; }
        public virtual SucursalCaja SucursalCaja { get; set; }
    }
}
