//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciadoCabecero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferenciadoCabecero()
        {
            this.ReferenciadoDetalle = new HashSet<ReferenciadoDetalle>();
        }
    
        public int PagoId { get; set; }
        public string ReferenciaId { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public decimal ImporteRestante { get; set; }
        public decimal ImporteTotal { get; set; }
        public int EstatusId { get; set; }
    
        public virtual Pago Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciadoDetalle> ReferenciadoDetalle { get; set; }
    }
}
