//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int RespuestaId { get; set; }
        public Nullable<int> AlumnoId { get; set; }
        public Nullable<int> PreguntaId { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public Nullable<System.TimeSpan> HoraGeneracion { get; set; }
        public Nullable<int> PreguntaTipoValoresId { get; set; }
        public string Comentario { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
