//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioTipoPagoConcepto
    {
        public int UsuarioTipoId { get; set; }
        public int PagoConceptoId { get; set; }
        public int OfertaEducativaId { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public System.TimeSpan HoraAsignacion { get; set; }
        public int UsuarioIdAsignacion { get; set; }
    
        public virtual PagoConcepto PagoConcepto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual UsuarioTipo UsuarioTipo { get; set; }
    }
}
