//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.2053.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.siged.sep.gob.mx/certificados/", IsNullable=false)]
public partial class Dec {
    
    private DecIpes ipesField;
    
    private DecRvoe rvoeField;
    
    private DecCarrera carreraField;
    
    private DecAlumno alumnoField;
    
    private DecExpedicion expedicionField;
    
    private DecAsignaturas asignaturasField;
    
    private DecDreoe dreoeField;
    
    private DecSepIpes sepIpesField;
    
    private string versionField;
    
    private string tipoCertificadoField;
    
    private string folioControlField;
    
    private string selloField;
    
    private string certificadoResponsableField;
    
    private string noCertificadoResponsableField;
    
    public Dec() {
        this.versionField = "1.0";
        this.tipoCertificadoField = "5";
    }
    
    /// <remarks/>
    public DecIpes Ipes {
        get {
            return this.ipesField;
        }
        set {
            this.ipesField = value;
        }
    }
    
    /// <remarks/>
    public DecRvoe Rvoe {
        get {
            return this.rvoeField;
        }
        set {
            this.rvoeField = value;
        }
    }
    
    /// <remarks/>
    public DecCarrera Carrera {
        get {
            return this.carreraField;
        }
        set {
            this.carreraField = value;
        }
    }
    
    /// <remarks/>
    public DecAlumno Alumno {
        get {
            return this.alumnoField;
        }
        set {
            this.alumnoField = value;
        }
    }
    
    /// <remarks/>
    public DecExpedicion Expedicion {
        get {
            return this.expedicionField;
        }
        set {
            this.expedicionField = value;
        }
    }
    
    /// <remarks/>
    public DecAsignaturas Asignaturas {
        get {
            return this.asignaturasField;
        }
        set {
            this.asignaturasField = value;
        }
    }
    
    /// <remarks/>
    public DecDreoe Dreoe {
        get {
            return this.dreoeField;
        }
        set {
            this.dreoeField = value;
        }
    }
    
    /// <remarks/>
    public DecSepIpes SepIpes {
        get {
            return this.sepIpesField;
        }
        set {
            this.sepIpesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string tipoCertificado {
        get {
            return this.tipoCertificadoField;
        }
        set {
            this.tipoCertificadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folioControl {
        get {
            return this.folioControlField;
        }
        set {
            this.folioControlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sello {
        get {
            return this.selloField;
        }
        set {
            this.selloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string certificadoResponsable {
        get {
            return this.certificadoResponsableField;
        }
        set {
            this.certificadoResponsableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noCertificadoResponsable {
        get {
            return this.noCertificadoResponsableField;
        }
        set {
            this.noCertificadoResponsableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecIpes {
    
    private DecIpesResponsable responsableField;
    
    private string idNombreInstitucionField;
    
    private string nombreInstitucionField;
    
    private string idCampusField;
    
    private string campusField;
    
    private string idEntidadFederativaField;
    
    private string entidadFederativaField;
    
    /// <remarks/>
    public DecIpesResponsable Responsable {
        get {
            return this.responsableField;
        }
        set {
            this.responsableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idNombreInstitucion {
        get {
            return this.idNombreInstitucionField;
        }
        set {
            this.idNombreInstitucionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombreInstitucion {
        get {
            return this.nombreInstitucionField;
        }
        set {
            this.nombreInstitucionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idCampus {
        get {
            return this.idCampusField;
        }
        set {
            this.idCampusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string campus {
        get {
            return this.campusField;
        }
        set {
            this.campusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idEntidadFederativa {
        get {
            return this.idEntidadFederativaField;
        }
        set {
            this.idEntidadFederativaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entidadFederativa {
        get {
            return this.entidadFederativaField;
        }
        set {
            this.entidadFederativaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecIpesResponsable {
    
    private string curpField;
    
    private string nombreField;
    
    private string primerApellidoField;
    
    private string segundoApellidoField;
    
    private string idCargoField;
    
    private string cargoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string curp {
        get {
            return this.curpField;
        }
        set {
            this.curpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string primerApellido {
        get {
            return this.primerApellidoField;
        }
        set {
            this.primerApellidoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string segundoApellido {
        get {
            return this.segundoApellidoField;
        }
        set {
            this.segundoApellidoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idCargo {
        get {
            return this.idCargoField;
        }
        set {
            this.idCargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cargo {
        get {
            return this.cargoField;
        }
        set {
            this.cargoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecRvoe {
    
    private string numeroField;
    
    private System.DateTime fechaExpedicionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaExpedicion {
        get {
            return this.fechaExpedicionField;
        }
        set {
            this.fechaExpedicionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecCarrera {
    
    private string idCarreraField;
    
    private string claveCarreraField;
    
    private string nombreCarreraField;
    
    private string idTipoPeriodoField;
    
    private string tipoPeriodoField;
    
    private string clavePlanField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string idCarrera {
        get {
            return this.idCarreraField;
        }
        set {
            this.idCarreraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string claveCarrera {
        get {
            return this.claveCarreraField;
        }
        set {
            this.claveCarreraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombreCarrera {
        get {
            return this.nombreCarreraField;
        }
        set {
            this.nombreCarreraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idTipoPeriodo {
        get {
            return this.idTipoPeriodoField;
        }
        set {
            this.idTipoPeriodoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipoPeriodo {
        get {
            return this.tipoPeriodoField;
        }
        set {
            this.tipoPeriodoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clavePlan {
        get {
            return this.clavePlanField;
        }
        set {
            this.clavePlanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecAlumno {
    
    private string numeroControlField;
    
    private string curpField;
    
    private string nombreField;
    
    private string primerApellidoField;
    
    private string segundoApellidoField;
    
    private string idGeneroField;
    
    private System.DateTime fechaNacimientoField;
    
    private string fotoField;
    
    private string firmaAutografaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numeroControl {
        get {
            return this.numeroControlField;
        }
        set {
            this.numeroControlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string curp {
        get {
            return this.curpField;
        }
        set {
            this.curpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string primerApellido {
        get {
            return this.primerApellidoField;
        }
        set {
            this.primerApellidoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string segundoApellido {
        get {
            return this.segundoApellidoField;
        }
        set {
            this.segundoApellidoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string idGenero {
        get {
            return this.idGeneroField;
        }
        set {
            this.idGeneroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaNacimiento {
        get {
            return this.fechaNacimientoField;
        }
        set {
            this.fechaNacimientoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string foto {
        get {
            return this.fotoField;
        }
        set {
            this.fotoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string firmaAutografa {
        get {
            return this.firmaAutografaField;
        }
        set {
            this.firmaAutografaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecExpedicion {
    
    private string idTipoCertificacionField;
    
    private string tipoCertificacionField;
    
    private System.DateTime fechaField;
    
    private string idLugarExpedicionField;
    
    private string lugarExpedicionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idTipoCertificacion {
        get {
            return this.idTipoCertificacionField;
        }
        set {
            this.idTipoCertificacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipoCertificacion {
        get {
            return this.tipoCertificacionField;
        }
        set {
            this.tipoCertificacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fecha {
        get {
            return this.fechaField;
        }
        set {
            this.fechaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idLugarExpedicion {
        get {
            return this.idLugarExpedicionField;
        }
        set {
            this.idLugarExpedicionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lugarExpedicion {
        get {
            return this.lugarExpedicionField;
        }
        set {
            this.lugarExpedicionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecAsignaturas {
    
    private DecAsignaturasAsignatura[] asignaturaField;
    
    private int totalField;
    
    private int asignadasField;
    
    private string promedioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Asignatura")]
    public DecAsignaturasAsignatura[] Asignatura {
        get {
            return this.asignaturaField;
        }
        set {
            this.asignaturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int asignadas {
        get {
            return this.asignadasField;
        }
        set {
            this.asignadasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string promedio {
        get {
            return this.promedioField;
        }
        set {
            this.promedioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecAsignaturasAsignatura {
    
    private string idAsignaturaField;
    
    private string claveAsignaturaField;
    
    private string nombreField;
    
    private string cicloField;
    
    private string calificacionField;
    
    private string idObservacionesField;
    
    private string observacionesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string idAsignatura {
        get {
            return this.idAsignaturaField;
        }
        set {
            this.idAsignaturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string claveAsignatura {
        get {
            return this.claveAsignaturaField;
        }
        set {
            this.claveAsignaturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ciclo {
        get {
            return this.cicloField;
        }
        set {
            this.cicloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string calificacion {
        get {
            return this.calificacionField;
        }
        set {
            this.calificacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string idObservaciones {
        get {
            return this.idObservacionesField;
        }
        set {
            this.idObservacionesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string observaciones {
        get {
            return this.observacionesField;
        }
        set {
            this.observacionesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecDreoe {
    
    private System.DateTime fechaDreoeField;
    
    private string selloDecField;
    
    private string noCertificadoDreoeField;
    
    private string curpField;
    
    private string nombreCompletoField;
    
    private string idCargoField;
    
    private string cargoField;
    
    private string selloDreoeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaDreoe {
        get {
            return this.fechaDreoeField;
        }
        set {
            this.fechaDreoeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string selloDec {
        get {
            return this.selloDecField;
        }
        set {
            this.selloDecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noCertificadoDreoe {
        get {
            return this.noCertificadoDreoeField;
        }
        set {
            this.noCertificadoDreoeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string curp {
        get {
            return this.curpField;
        }
        set {
            this.curpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombreCompleto {
        get {
            return this.nombreCompletoField;
        }
        set {
            this.nombreCompletoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idCargo {
        get {
            return this.idCargoField;
        }
        set {
            this.idCargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cargo {
        get {
            return this.cargoField;
        }
        set {
            this.cargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string selloDreoe {
        get {
            return this.selloDreoeField;
        }
        set {
            this.selloDreoeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.siged.sep.gob.mx/certificados/")]
public partial class DecSepIpes {
    
    private string versionField;
    
    private string folioDigitalField;
    
    private System.DateTime fechaSepIpesField;
    
    private string selloDreoeField;
    
    private string noCertificadoSepIpesField;
    
    private string selloSepIpesField;
    
    public DecSepIpes() {
        this.versionField = "1.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folioDigital {
        get {
            return this.folioDigitalField;
        }
        set {
            this.folioDigitalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaSepIpes {
        get {
            return this.fechaSepIpesField;
        }
        set {
            this.fechaSepIpesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string selloDreoe {
        get {
            return this.selloDreoeField;
        }
        set {
            this.selloDreoeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noCertificadoSepIpes {
        get {
            return this.noCertificadoSepIpesField;
        }
        set {
            this.noCertificadoSepIpesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string selloSepIpes {
        get {
            return this.selloSepIpesField;
        }
        set {
            this.selloSepIpesField = value;
        }
    }
}
