//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.33440.
// 
namespace DTO.SEP
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.siged.sep.gob.mx/titulos/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://www.siged.sep.gob.mx/titulos/", IsNullable = false)]
    public partial class Autenticacion
    {

        private string versionField;

        private string folioDigitalField;

        private System.DateTime fechaAutenticacionField;

        private string selloTituloField;

        private string noCertificadoAutoridadField;

        private string selloAutenticacionField;

        public Autenticacion()
        {
            this.versionField = "1.0";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string folioDigital
        {
            get
            {
                return this.folioDigitalField;
            }
            set
            {
                this.folioDigitalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime fechaAutenticacion
        {
            get
            {
                return this.fechaAutenticacionField;
            }
            set
            {
                this.fechaAutenticacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string selloTitulo
        {
            get
            {
                return this.selloTituloField;
            }
            set
            {
                this.selloTituloField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string noCertificadoAutoridad
        {
            get
            {
                return this.noCertificadoAutoridadField;
            }
            set
            {
                this.noCertificadoAutoridadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string selloAutenticacion
        {
            get
            {
                return this.selloAutenticacionField;
            }
            set
            {
                this.selloAutenticacionField = value;
            }
        }
    }
}