//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccionSEP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccionSEP()
        {
            this.AlumnoTituloAccion = new HashSet<AlumnoTituloAccion>();
        }
    
        public int AccionSEPId { get; set; }
        public int NumeroLote { get; set; }
        public string Mensaje { get; set; }
        public int MovimientoId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual MovimientoSEP MovimientoSEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoTituloAccion> AlumnoTituloAccion { get; set; }
    }
}
