//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoTitulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlumnoTitulo()
        {
            this.AlumnoTituloAccion = new HashSet<AlumnoTituloAccion>();
            this.UsuarioResponsable = new HashSet<UsuarioResponsable>();
        }
    
        public int AlumnoTituloId { get; set; }
        public int AlumnoId { get; set; }
        public int AlumnoOfertaEducativaId { get; set; }
        public int AutorizacionReconocimientoId { get; set; }
        public System.DateTime FechaExpedicion { get; set; }
        public int ModalidadTitulacionId { get; set; }
        public System.DateTime FechaExamenProfesional { get; set; }
        public System.DateTime FechaExencionExamenProfecional { get; set; }
        public bool ServicioSocial { get; set; }
        public int FundamentoLegalId { get; set; }
        public int EntidadFederativaIdExpedicion { get; set; }
        public int AlumnoAntecedenteId { get; set; }
        public int Libro { get; set; }
        public int Foja { get; set; }
        public int UsuarioId { get; set; }
        public int MovimientoId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual EntidadFederativa EntidadFederativa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual AlumnoAntecedente1 AlumnoAntecedente1 { get; set; }
        public virtual AlumnoOfertaEducativa AlumnoOfertaEducativa { get; set; }
        public virtual AutorizacionReconocimiento AutorizacionReconocimiento { get; set; }
        public virtual FundamentoLegal FundamentoLegal { get; set; }
        public virtual ModalidadTitulacion ModalidadTitulacion { get; set; }
        public virtual MovimientoSEP MovimientoSEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoTituloAccion> AlumnoTituloAccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioResponsable> UsuarioResponsable { get; set; }
    }
}
