//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoTituloAccion
    {
        public int AlumnoTituloAccionId { get; set; }
        public int AccionSEPId { get; set; }
        public int AlumnoTituloId { get; set; }
    
        public virtual AccionSEP AccionSEP { get; set; }
        public virtual AlumnoTitulo AlumnoTitulo { get; set; }
    }
}
