//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoMovimientoTurno
    {
        public int AlumnoMovimientoId { get; set; }
        public Nullable<int> TurnoId { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Turno Turno { get; set; }
        public virtual AlumnoMovimiento AlumnoMovimiento { get; set; }
    }
}
