//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoAntecedenteBitacora
    {
        public int AlumnoId { get; set; }
        public int AntecedenteTipoId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int AreaAcademicaId { get; set; }
        public string Procedencia { get; set; }
        public decimal Promedio { get; set; }
        public int Anio { get; set; }
        public int MesId { get; set; }
        public bool EsEquivalencia { get; set; }
        public string EscuelaEquivalencia { get; set; }
        public int PaisId { get; set; }
        public int EntidadFederativaId { get; set; }
        public bool EsTitulado { get; set; }
        public string TitulacionMedio { get; set; }
        public int MedioDifusionId { get; set; }
        public int UsuarioId { get; set; }
        public int UsuarioIdBitacora { get; set; }
        public System.DateTime FechaBitacora { get; set; }
        public System.TimeSpan HoraBitacora { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
