//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoCuatrimestreBitacora
    {
        public int AlumnoId { get; set; }
        public int OfertaEducativaId { get; set; }
        public int Cuatrimestre { get; set; }
        public int Anio { get; set; }
        public int PeriodoId { get; set; }
        public Nullable<bool> esRegular { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public System.TimeSpan HoraAsignacion { get; set; }
        public int UsuarioId { get; set; }
    }
}
