//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoOfertaEducativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlumnoOfertaEducativa()
        {
            this.AlumnoTitulo = new HashSet<AlumnoTitulo>();
        }
    
        public int AlumnoOfertaEducativaId { get; set; }
        public string InstitucionId { get; set; }
        public int OfertaEducativaId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public string RVOE { get; set; }
    
        public virtual OfertaEducativa OfertaEducativa { get; set; }
        public virtual Institucion Institucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoTitulo> AlumnoTitulo { get; set; }
    }
}
