//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        public int OfertaEducativaId { get; set; }
        public string AsignaturaId { get; set; }
        public string Descripcion { get; set; }
        public int NivelAcademicoId { get; set; }
        public decimal Creditos { get; set; }
        public string AsignaturaSeriacionId { get; set; }
        public int EstatusId { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual OfertaEducativa OfertaEducativa { get; set; }
    }
}
