//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asociacion()
        {
            this.PolizaConsecutivo = new HashSet<PolizaConsecutivo>();
            this.PolizaCuadre = new HashSet<PolizaCuadre>();
            this.PolizaNumeracion = new HashSet<PolizaNumeracion>();
            this.ReferenciadoArchivoBitacora = new HashSet<ReferenciadoArchivoBitacora>();
            this.PolizaConfiguracion = new HashSet<PolizaConfiguracion>();
        }
    
        public int AsociacionId { get; set; }
        public string Descripcion { get; set; }
        public string Abreviacion { get; set; }
        public string Carpeta { get; set; }
    
        public virtual AsociacionDetalle AsociacionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaConsecutivo> PolizaConsecutivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaCuadre> PolizaCuadre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaNumeracion> PolizaNumeracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciadoArchivoBitacora> ReferenciadoArchivoBitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaConfiguracion> PolizaConfiguracion { get; set; }
    }
}
