//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancoTerminal
    {
        public int BancoTerminalId { get; set; }
        public string Descripcion { get; set; }
        public bool TieneMSI { get; set; }
        public string CuentaContable { get; set; }
        public int PagoMetodoId { get; set; }
        public int EstatusId { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual PagoMetodo PagoMetodo { get; set; }
    }
}
