//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionesAntecedente
    {
        public int AlumnoId { get; set; }
        public int OfertaEducativaId { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> PeriodoId { get; set; }
        public Nullable<int> NoMaterias { get; set; }
        public string CalificacionMaterias { get; set; }
        public Nullable<int> NoBajas { get; set; }
        public string BajaMaterias { get; set; }
    }
}
