//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoResponsable
    {
        public int CertificadoResponsableId { get; set; }
        public int UsuarioId { get; set; }
        public int AlumnoCertificadoId { get; set; }
        public string Comentario { get; set; }
        public bool Aprobo { get; set; }
    
        public virtual AlumnoCertificado AlumnoCertificado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
