//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLEGIATURA
    {
        public int AlumnoId { get; set; }
        public int Anio { get; set; }
        public int PeriodoId { get; set; }
        public int OfertaEducativaID { get; set; }
        public string DescOferta { get; set; }
        public int PagoConceptoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Materias { get; set; }
        public Nullable<decimal> TotalPagado { get; set; }
        public Nullable<decimal> InscripcionPagado { get; set; }
        public Nullable<decimal> TotalDeuda { get; set; }
        public Nullable<decimal> InscripcionDeuda { get; set; }
        public Nullable<int> Inscrito { get; set; }
        public Nullable<int> EsEmpresa { get; set; }
    }
}
