//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunicado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comunicado()
        {
            this.ComunicadoUsuario = new HashSet<ComunicadoUsuario>();
        }
    
        public int ComunicadoId { get; set; }
        public int Anio { get; set; }
        public int PeriodoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UsuarioId { get; set; }
        public string Asunto { get; set; }
        public string Documento { get; set; }
    
        public virtual Periodo Periodo { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicadoUsuario> ComunicadoUsuario { get; set; }
    }
}
