//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComunicadoUsuario
    {
        public int ComunicadoUsuarioId { get; set; }
        public int ComunicadoId { get; set; }
        public int UsuarioId { get; set; }
        public int UsuarioTipoId { get; set; }
        public bool Fallido { get; set; }
        public string Mensaje { get; set; }
    
        public virtual Comunicado Comunicado { get; set; }
        public virtual UsuarioTipo UsuarioTipo { get; set; }
    }
}
