//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuotaIncremento
    {
        public int Anio { get; set; }
        public int PeriodoId { get; set; }
        public decimal ImporteIncremento { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaAutorizacion { get; set; }
        public System.TimeSpan HoraAutorizacion { get; set; }
        public string Observaciones { get; set; }
        public int OfertaEducativaTipoId { get; set; }
        public int PagoConceptoId { get; set; }
    
        public virtual OfertaEducativaTipo OfertaEducativaTipo { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
