//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosClipper
    {
        public int DATOID { get; set; }
        public int CLAVE { get; set; }
        public string NOMBRE { get; set; }
        public string FECHANACI { get; set; }
        public string EDOCIVI { get; set; }
        public string SEXO { get; set; }
        public string NACIONA { get; set; }
        public string MATRICULA { get; set; }
        public string SISTPAGO { get; set; }
        public string CALLECAS { get; set; }
        public string COLONIACAS { get; set; }
        public string DELEGACAS { get; set; }
        public string ESTADOCAS { get; set; }
        public string CPCAS { get; set; }
        public string TELCAS { get; set; }
        public string CALLEOFI { get; set; }
        public string COLONIAOFI { get; set; }
        public string DELEGAOFI { get; set; }
        public string ESTADOOFI { get; set; }
        public string CPOFI { get; set; }
        public string TELOFI { get; set; }
        public string FAXOFI { get; set; }
        public string FECHAALTA { get; set; }
        public string TIPOSOCIO { get; set; }
        public string FPAGO { get; set; }
        public string PAGADOHAS { get; set; }
        public string STATUS { get; set; }
        public string DESAUTORI { get; set; }
        public string BECADEPO { get; set; }
        public string BECASEP { get; set; }
        public string SIBAJA { get; set; }
        public string FECHABAJA { get; set; }
        public string MOTIVOBAJA { get; set; }
        public string CUATRIMEST { get; set; }
        public string FINANMTO { get; set; }
        public string TURNO { get; set; }
        public string GRUPO { get; set; }
        public string ACTIVO { get; set; }
        public string MAILTUTOR { get; set; }
        public string MAILALUMNO { get; set; }
        public string EXAMMED { get; set; }
        public string RECURSANDO { get; set; }
        public string INSCRIP { get; set; }
        public string REFER1 { get; set; }
        public string TELEF1 { get; set; }
        public string REFER2 { get; set; }
        public string TELEF2 { get; set; }
        public string FPDEPOR { get; set; }
        public string NOM { get; set; }
        public string AP_PAT { get; set; }
        public string AP_MAT { get; set; }
    }
}
