//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defectos
    {
        public int DefectoId { get; set; }
        public Nullable<System.DateTime> FechaDefecto { get; set; }
        public Nullable<int> AlumnoId { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> PeriodoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> UsuarioidReporto { get; set; }
        public Nullable<int> UsuarioidResolvio { get; set; }
        public string DescripcionSolucion { get; set; }
    }
}
