//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocentePublicacion
    {
        public int DocenteId { get; set; }
        public Nullable<int> PublicacionTipoId { get; set; }
        public string Titulo { get; set; }
        public string TituloPublicacion { get; set; }
        public string Editorial { get; set; }
        public string NoVolumen { get; set; }
        public string NoPagina { get; set; }
        public Nullable<int> PaisId { get; set; }
        public Nullable<int> EntidadFederativaId { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.TimeSpan> HoraRegistro { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    }
}
