//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocenteEstudio
    {
        public int EstudioId { get; set; }
        public Nullable<int> DocenteId { get; set; }
        public string Institucion { get; set; }
        public Nullable<int> OfertaEducativaTipoId { get; set; }
        public string Carrera { get; set; }
        public Nullable<bool> Cedula { get; set; }
        public Nullable<bool> Titulo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> EstatusId { get; set; }
    }
}
