//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocenteEstudioPeriodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocenteEstudioPeriodo()
        {
            this.CancelacionDocenteEstudio = new HashSet<CancelacionDocenteEstudio>();
            this.VistoBuenoEstudio = new HashSet<VistoBuenoEstudio>();
        }
    
        public int DocenteEstudioPeriodoId { get; set; }
        public int DocenteId { get; set; }
        public int Anio { get; set; }
        public int PeriodoId { get; set; }
        public int EstudioId { get; set; }
        public bool EstatusId { get; set; }
    
        public virtual Periodo Periodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelacionDocenteEstudio> CancelacionDocenteEstudio { get; set; }
        public virtual Docente Docente { get; set; }
        public virtual DocenteEstudio DocenteEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VistoBuenoEstudio> VistoBuenoEstudio { get; set; }
    }
}
