//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocenteEstudioDocumento
    {
        public int EstudioId { get; set; }
        public int DocuentoTipoId { get; set; }
        public string DocumentoUrl { get; set; }
    
        public virtual DocenteEstudio DocenteEstudio { get; set; }
        public virtual DocumentoTipo DocumentoTipo { get; set; }
    }
}
