//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocenteActualizacion
    {
        public int DocenteActualizacionId { get; set; }
        public int DocenteId { get; set; }
        public int ActualizacionId { get; set; }
        public bool EsCurso { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual DocenteCurso DocenteCurso { get; set; }
        public virtual DocenteEstudio DocenteEstudio { get; set; }
    }
}
