//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Grupo = new HashSet<Grupo>();
        }
    
        public int EmpresaId { get; set; }
        public string RFC { get; set; }
        public string RazonSocial { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaVigencia { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual DatosFiscales DatosFiscales { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual EmpresaDetalle EmpresaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo> Grupo { get; set; }
    }
}
