//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdiomaGrupoAlumno
    {
        public int AlumnoId { get; set; }
        public int IdiomaGrupoId { get; set; }
        public Nullable<int> OfertaEducativaId { get; set; }
        public string TipoCurso { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<System.TimeSpan> HoraAsignacion { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> EstatusId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual IdiomaGrupo IdiomaGrupo { get; set; }
        public virtual OfertaEducativa OfertaEducativa { get; set; }
    }
}
