//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitucionOfertaEducativa
    {
        public int InstitucionOfertaEducativaId { get; set; }
        public string InstitucionId { get; set; }
        public int CampusId { get; set; }
        public int OfertaEducativaId { get; set; }
        public string ClaveOfertaEducativa { get; set; }
    
        public virtual OfertaEducativa OfertaEducativa { get; set; }
        public virtual Campus Campus { get; set; }
        public virtual Institucion Institucion { get; set; }
    }
}
