//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaApertura
    {
        public int MateriaAperturaId { get; set; }
        public Nullable<int> MateriaId { get; set; }
        public Nullable<int> MateriaTipoId { get; set; }
        public Nullable<decimal> Duracion { get; set; }
        public Nullable<int> GrupoId { get; set; }
        public Nullable<int> NoAlumnos { get; set; }
        public Nullable<int> TurnoId { get; set; }
        public Nullable<int> DocenteId { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> PeriodoId { get; set; }
        public Nullable<bool> EsCompartida { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<System.TimeSpan> HoraApertura { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> EstatusId { get; set; }
    }
}
