//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaEducativaPlan
    {
        public int OfertaEducativaPlanId { get; set; }
        public int OfertaEducativaTipoId { get; set; }
        public int PagoPlanId { get; set; }
    
        public virtual OfertaEducativaTipo OfertaEducativaTipo { get; set; }
        public virtual PagoPlan PagoPlan { get; set; }
    }
}
