//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoDetalle
    {
        public int PagoParcialId { get; set; }
        public int PagoMetodoId { get; set; }
        public decimal Importe { get; set; }
    
        public virtual PagoMetodo PagoMetodo { get; set; }
        public virtual PagoParcial PagoParcial { get; set; }
    }
}
