//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoParcialBitacora
    {
        public int PagoParcialId { get; set; }
        public int PagoId { get; set; }
        public Nullable<int> SucursalCajaId { get; set; }
        public Nullable<int> ReciboId { get; set; }
        public decimal Pago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public System.TimeSpan HoraPago { get; set; }
        public int EstatusId { get; set; }
        public bool TieneMovimientos { get; set; }
        public int PagoTipoId { get; set; }
        public Nullable<int> ReferenciaProcesadaId { get; set; }
        public System.DateTime FechaBitacora { get; set; }
        public System.TimeSpan HoraBitacora { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
