//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoCancelacionSolicitud
    {
        public int SolicitudId { get; set; }
        public Nullable<int> PagoId { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.TimeSpan> HoraSolicitud { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> UsuarioIdSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAplicacion { get; set; }
        public Nullable<System.TimeSpan> HoraAplicacion { get; set; }
        public Nullable<int> UsuarioIdAutoriza { get; set; }
        public Nullable<int> EstatusId { get; set; }
    }
}
