//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoAnticipado
    {
        public int Anio { get; set; }
        public int PeriodoId { get; set; }
        public int PeriodoAnticipadoId { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public decimal ImporteDescuento { get; set; }
        public int OfertaEducativaTipoId { get; set; }
        public int PagoConceptoId { get; set; }
    
        public virtual OfertaEducativaTipo OfertaEducativaTipo { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
