//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaAjuste
    {
        public int PagoId { get; set; }
        public System.DateTime FechaAjuste { get; set; }
        public decimal Importe { get; set; }
        public string CuentaOrigen { get; set; }
        public string CuentaDestino { get; set; }
        public int EstatusId { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
