//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntaConfiguracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreguntaConfiguracion()
        {
            this.Pregunta = new HashSet<Pregunta>();
        }
    
        public int PreguntaConfiguracionId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> PreguntaTipoId { get; set; }
        public Nullable<bool> esCompuesta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregunta> Pregunta { get; set; }
        public virtual PreguntaCompuesta PreguntaCompuesta { get; set; }
        public virtual PreguntaTipo PreguntaTipo { get; set; }
    }
}
