//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntaCompuesta
    {
        public int PreguntaConfiguracionId { get; set; }
        public int PreguntaTipoValoresId { get; set; }
        public Nullable<int> PreguntaTipoId { get; set; }
    
        public virtual PreguntaConfiguracion PreguntaConfiguracion { get; set; }
        public virtual PreguntaTipo PreguntaTipo { get; set; }
        public virtual PreguntaTipoValores PreguntaTipoValores { get; set; }
    }
}
