//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntaTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreguntaTipo()
        {
            this.PreguntaCompuesta = new HashSet<PreguntaCompuesta>();
            this.PreguntaConfiguracion = new HashSet<PreguntaConfiguracion>();
            this.PreguntaTipoValores = new HashSet<PreguntaTipoValores>();
        }
    
        public int PreguntaTipoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ValorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntaCompuesta> PreguntaCompuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntaConfiguracion> PreguntaConfiguracion { get; set; }
        public virtual PreguntaValor PreguntaValor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntaTipoValores> PreguntaTipoValores { get; set; }
    }
}
