//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclasificacion
    {
        public int ReclasificacionId { get; set; }
        public int PagoParcialId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaReclasificacion { get; set; }
        public System.TimeSpan HoraReclasificacion { get; set; }
        public decimal Importe { get; set; }
        public int ReclasificacionTipoId { get; set; }
    
        public virtual PagoParcial PagoParcial { get; set; }
        public virtual ReclasificacionTipo ReclasificacionTipo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
