//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciaDonativo
    {
        public int ReferenciaDonativoId { get; set; }
        public int ReferenciaProcesadaIdOrigen { get; set; }
        public int ReferenciaProcesadaIdDestino { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual ReferenciaProcesada ReferenciaProcesada { get; set; }
        public virtual ReferenciaProcesada ReferenciaProcesada1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
