//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciaProcesada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferenciaProcesada()
        {
            this.AlumnoSaldoDetalle = new HashSet<AlumnoSaldoDetalle>();
            this.PagoParcial = new HashSet<PagoParcial>();
            this.ReferenciadoDetalle = new HashSet<ReferenciadoDetalle>();
        }
    
        public int ReferenciaProcesadaId { get; set; }
        public string ReferenciaId { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Importe { get; set; }
        public decimal Restante { get; set; }
        public int AlumnoId { get; set; }
        public int ReferenciaTipoId { get; set; }
        public string Observaciones { get; set; }
        public bool SeGasto { get; set; }
        public bool EsIngles { get; set; }
        public int EstatusId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoSaldoDetalle> AlumnoSaldoDetalle { get; set; }
        public virtual Estatus Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoParcial> PagoParcial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciadoDetalle> ReferenciadoDetalle { get; set; }
        public virtual ReferenciaTipo ReferenciaTipo { get; set; }
    }
}
