//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salon
    {
        public int SalonId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> SedeId { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public string Detalle { get; set; }
    }
}
