//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudInscripcion
    {
        public int AlumnoId { get; set; }
        public int OfertaEducativaId { get; set; }
        public int Anio { get; set; }
        public int PeriodoId { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.TimeSpan HoraSolicitud { get; set; }
        public int SolicitudUsuarioId { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public Nullable<System.TimeSpan> HoraAutorizacion { get; set; }
        public Nullable<int> AutorizoUsuarioId { get; set; }
        public int EstatusId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual OfertaEducativa OfertaEducativa { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
