//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class spReporteBecasDetalle
    {
        public Nullable<int> AlumnoId { get; set; }
        public Nullable<int> OfertaEducativaId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> CostoIns { get; set; }
        public Nullable<int> AnticipadoIns { get; set; }
        public Nullable<decimal> AnticipadoInsPor { get; set; }
        public Nullable<int> BecaIns { get; set; }
        public Nullable<decimal> BecaInsPor { get; set; }
        public Nullable<decimal> DesTotalIns { get; set; }
        public Nullable<decimal> DesTotalInsPor { get; set; }
        public Nullable<decimal> TotalIns { get; set; }
        public Nullable<decimal> CostoCol { get; set; }
        public Nullable<int> AnticipadoCol { get; set; }
        public Nullable<decimal> AnticipadoColPor { get; set; }
        public Nullable<int> BecaCol { get; set; }
        public Nullable<decimal> BecaColPor { get; set; }
        public Nullable<int> BecaDeportiva { get; set; }
        public Nullable<decimal> BecaDeportivaPor { get; set; }
        public Nullable<int> PromoCasa { get; set; }
        public Nullable<decimal> PromoCasaPor { get; set; }
        public Nullable<decimal> DesTotalCol { get; set; }
        public Nullable<decimal> DesTotalColPor { get; set; }
        public Nullable<decimal> TotalCol { get; set; }
        public string EsEmpresa { get; set; }
    }
}
