//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class spReporteBecasConcentrado
    {
        public string Descripcion { get; set; }
        public Nullable<int> TotalAlumnos { get; set; }
        public Nullable<int> AlumnosConBeca { get; set; }
        public Nullable<decimal> CargosInscripcion { get; set; }
        public Nullable<decimal> PromedioAnticipadoPor { get; set; }
        public Nullable<int> PromedioAnticipado_ { get; set; }
        public Nullable<decimal> PromedioBecaInscripcionPor { get; set; }
        public Nullable<int> PromedioBecaInscripcion_ { get; set; }
        public Nullable<decimal> TotalDescuentoInscripcion { get; set; }
        public Nullable<decimal> CargosColegiatura { get; set; }
        public Nullable<decimal> PromedioAnticipadoPorColegiatura { get; set; }
        public Nullable<int> PromedioAnticipado_Colegiatura { get; set; }
        public Nullable<decimal> BecaPromedioPor { get; set; }
        public Nullable<int> BecaPromedio_ { get; set; }
        public Nullable<decimal> BecaDeportivaPor { get; set; }
        public Nullable<int> BecaDeportivaPromedio_ { get; set; }
        public Nullable<decimal> PromoCasaPor { get; set; }
        public Nullable<int> PromoCasa_ { get; set; }
        public Nullable<decimal> TotalDescuentoColegiatura { get; set; }
    }
}
