//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla2
    {
        public int ConsecutivoId { get; set; }
        public int AlumnoId { get; set; }
        public int TipoAdeudoId { get; set; }
        public int Valor { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public System.TimeSpan HoraOperacion { get; set; }
        public int UsuarioId { get; set; }
    }
}
