//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempAdeudo
    {
        public int AlumnoId { get; set; }
        public decimal Adeudo { get; set; }
        public int Tipo { get; set; }
        public int OfertaEducativaId { get; set; }
    }
}
