//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioDetalle
    {
        public int UsuarioId { get; set; }
        public int GeneroId { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Email { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Genero Genero { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
