//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioPermiso
    {
        public int UsuarioId { get; set; }
        public int IngresosId { get; set; }
        public int UsuarioIdAsignacion { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public System.TimeSpan HoraAsignacion { get; set; }
    
        public virtual IngresosPermiso IngresosPermiso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
