//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ACJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ACJEntities : DbContext
    {
        public ACJEntities()
            : base("name=ACJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SPS_CALIFICACIONES_Result> SPS_CALIFICACIONES(Nullable<int> alumnoId)
        {
            var alumnoIdParameter = alumnoId.HasValue ?
                new ObjectParameter("AlumnoId", alumnoId) :
                new ObjectParameter("AlumnoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPS_CALIFICACIONES_Result>("SPS_CALIFICACIONES", alumnoIdParameter);
        }
    }
}
