//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoReferenciaBitacora
    {
        public int BitacoraId { get; set; }
        public int AlumnoId { get; set; }
        public int OfertaEducativaId { get; set; }
        public int PagoConceptoId { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> PeriodoId { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public System.TimeSpan HoraGeneracion { get; set; }
        public int PagoId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual PagoConcepto PagoConcepto { get; set; }
    }
}
