//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoDetalle
    {
        public int AlumnoId { get; set; }
        public int GeneroId { get; set; }
        public int EstadoCivilId { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string CURP { get; set; }
        public int PaisId { get; set; }
        public int EntidadFederativaId { get; set; }
        public Nullable<int> EntidadNacimientoId { get; set; }
        public int MunicipioId { get; set; }
        public string CP { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string NoExterior { get; set; }
        public string NoInterior { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoOficina { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public int ProspectoId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual EntidadFederativa EntidadFederativa { get; set; }
        public virtual EntidadFederativa EntidadFederativa1 { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Prospecto Prospecto { get; set; }
    }
}
