//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoImagenDetalle
    {
        public int AlumnoId { get; set; }
        public string Extension { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public System.TimeSpan HoraCarga { get; set; }
        public int UsuarioIdCarga { get; set; }
    
        public virtual AlumnoImagen AlumnoImagen { get; set; }
    }
}
