//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraReinscripcionAdeudo
    {
        public int AlumnoId { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public System.TimeSpan HoraOperacion { get; set; }
        public bool EsBiblioteca { get; set; }
        public bool EsChocolates { get; set; }
        public int UsuarioId { get; set; }
        public string Observaciones { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
