//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaConfiguracion
    {
        public int ConfiguracionId { get; set; }
        public string ImpresoraRecibo { get; set; }
        public string ImpresoraReporteria { get; set; }
        public int SucursalCajaId { get; set; }
    
        public virtual SucursalCaja SucursalCaja { get; set; }
    }
}
