//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoDetalle
    {
        public int GrupoId { get; set; }
        public decimal PorcentajeInscripcion { get; set; }
        public Nullable<decimal> PorcentajeColegiatura { get; set; }
        public bool SiempreInscripcion { get; set; }
        public int NoPagos { get; set; }
        public int CuotaId { get; set; }
        public bool EsCuotaCongelada { get; set; }
    
        public virtual Cuota Cuota { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
