//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoPagare
    {
        public int PagoId { get; set; }
        public int PagareId { get; set; }
        public string ReferenciaId { get; set; }
    
        public virtual Pagare Pagare { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
