//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoParcial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PagoParcial()
        {
            this.PagoDetalle = new HashSet<PagoDetalle>();
        }
    
        public int PagoId { get; set; }
        public int SucursalCajaId { get; set; }
        public int ReciboId { get; set; }
        public string Serie { get; set; }
        public decimal Pago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public System.TimeSpan HoraPago { get; set; }
        public bool EsReferencia { get; set; }
        public int EstatusId { get; set; }
        public Nullable<int> ReferenciaProcesadaId { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual Pago Pago1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoDetalle> PagoDetalle { get; set; }
        public virtual Recibo Recibo { get; set; }
        public virtual ReferenciaProcesada ReferenciaProcesada { get; set; }
    }
}
