//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoDetalle
    {
        public int PagoId { get; set; }
        public int SucursalCajaId { get; set; }
        public int ReciboId { get; set; }
        public int PagoMetodoId { get; set; }
        public decimal Monto { get; set; }
        public int ConceptoPagoId { get; set; }
    
        public virtual PagoMetodo PagoMetodo { get; set; }
        public virtual PagoParcial PagoParcial { get; set; }
    }
}
