//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaCabeceroLayout
    {
        public int PolizaTipoId { get; set; }
        public int ConfiguracionId { get; set; }
        public string Descripcion { get; set; }
        public string ValorDefault { get; set; }
        public int Longitud { get; set; }
        public bool TieneEspacio { get; set; }
    
        public virtual PolizaTipo PolizaTipo { get; set; }
    }
}
