//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectoDetalle
    {
        public int ProspectoId { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string CURP { get; set; }
        public Nullable<int> GeneroId { get; set; }
        public Nullable<int> EstadoCivilId { get; set; }
        public Nullable<int> PaisId { get; set; }
        public Nullable<int> EntidadFederativaId { get; set; }
        public Nullable<int> MunicipioId { get; set; }
        public string CP { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string NoExterior { get; set; }
        public string NoInterior { get; set; }
        public string PrepaProcedencia { get; set; }
        public Nullable<int> PrepaArea { get; set; }
        public Nullable<int> PrepaAnio { get; set; }
        public Nullable<int> PrepaMes { get; set; }
        public Nullable<int> PrepaPaisId { get; set; }
        public Nullable<decimal> PrepaPromedio { get; set; }
        public Nullable<int> PrepaEntidadId { get; set; }
        public Nullable<bool> EsEquivalencia { get; set; }
        public string UniversidadProcedencia { get; set; }
        public Nullable<int> UniversidadPaisId { get; set; }
        public Nullable<int> UniversidadEntidadId { get; set; }
        public string UniversidadMotivo { get; set; }
        public Nullable<bool> EsTitulado { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> SucursalId { get; set; }
        public Nullable<int> OfertaEducativaTipoId { get; set; }
        public Nullable<int> OfertaEducativaId { get; set; }
        public Nullable<int> TurnoId { get; set; }
        public Nullable<int> MedioDifusionId { get; set; }
        public string Observaciones { get; set; }
    
        public virtual AreaAcademica AreaAcademica { get; set; }
        public virtual EntidadFederativa EntidadFederativa { get; set; }
        public virtual EntidadFederativa EntidadFederativa1 { get; set; }
        public virtual EntidadFederativa EntidadFederativa2 { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual MedioDifusion MedioDifusion { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual OfertaEducativa OfertaEducativa { get; set; }
        public virtual OfertaEducativaTipo OfertaEducativaTipo { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Pais Pais1 { get; set; }
        public virtual Pais Pais2 { get; set; }
        public virtual Prospecto Prospecto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
