//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciadoDetalleBitacora
    {
        public int PagoId { get; set; }
        public string ReferenciaId { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Importe { get; set; }
        public System.TimeSpan HoraProcesado { get; set; }
        public System.DateTime FechaProcesado { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaBitacora { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ReferenciadoCabeceroBitacora ReferenciadoCabeceroBitacora { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
