//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteEstadoCuentaDescuento
    {
        public int PagoConceptoId { get; set; }
        public string Descripcion { get; set; }
        public int TipoDescuento { get; set; }
        public string TipoDescuentoDesc { get; set; }
    }
}
