//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saldos
    {
        public int AlumnoId { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public int Anio { get; set; }
        public int PeriodoID { get; set; }
        public int OfertaEducativaId { get; set; }
        public string descripcion { get; set; }
        public string Grupo { get; set; }
        public decimal TotalCargos { get; set; }
        public decimal TotalAbonos { get; set; }
        public decimal SaldoSQL { get; set; }
        public decimal SaldoCLIPPER { get; set; }
        public decimal SaldoPeriodoAnterior { get; set; }
        public decimal CargosCarrera { get; set; }
        public decimal CargosMaterias { get; set; }
        public decimal CargosAsesoriaEspecial { get; set; }
        public decimal CargosExamenDiagnostico { get; set; }
        public decimal CargosIngles { get; set; }
        public decimal Recargos { get; set; }
        public decimal PagoAnticipado { get; set; }
        public decimal BecaColegiatura { get; set; }
        public decimal DescuentoInscripcion { get; set; }
        public decimal DescuentoIngles { get; set; }
        public decimal OtrosDescuentos { get; set; }
        public decimal TotalDescuentos { get; set; }
        public decimal AbonoCaja { get; set; }
        public decimal AbonoReferenciado20161 { get; set; }
        public decimal AbonoReferenciado20162 { get; set; }
        public Nullable<int> TipoAlumno { get; set; }
    }
}
