//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalAnuncio
    {
        public int AnuncioId { get; set; }
        public int SucursalId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
    }
}
